import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const RobotoFlex = localFont({
  src: "../../public/fonts/RobotoFlex.woff2",
  variable: "--RobotoFlex",
  display: "swap",
});

const RobotoFlexii = localFont({
  src: "../../public/fonts/RobotoFlexii.woff2",
  variable: "--RobotoFlexii",
  display: "swap",
});

const RobotoCondensed = localFont({
  src: "../../public/fonts/RobotoCondensed.woff2",
  variable: "--RobotoCondensed",
  display: "swap",
});

const Roboto = localFont({
  src: "../../public/fonts/Roboto.woff2",
  variable: "--Roboto",
  display: "swap",
});

const GeistMono = localFont({
  src: "../../public/fonts/GeistMono.woff2",
  variable: "--GeistMono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${RobotoFlex.variable} ${RobotoFlexii.variable} ${RobotoCondensed.variable} ${Roboto.variable} ${GeistMono.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
